"""add is_admin to users

Revision ID: a8cd879dd7ae
Revises: 1397a47ec5f5
Create Date: 2026-04-30 06:26:14.228033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cd879dd7ae'
down_revision: Union[str, Sequence[str], None] = '1397a47ec5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', 
                  sa.Column(
                      'is_admin', 
                      sa.Boolean(), 
                      nullable=False,
                      server_default=sa.false()
        )
    )

    op.alter_column('users', 'is_admin, server_default=None')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
